version: "3.3"

services:
  chrome:
    image: selenium/standalone-chrome:4.3.0-20220706
    ports:
      - "4444:4444"
  tg_bot:
    build:
      context: .
    depends_on:
      - chrome
    volumes:
      - ./:/app/
    command: bash -c "diesel migration run && tg_bot"